<?php
$z[0]=Array("channel","\r\n <LI><a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,8)'/]\" >[field:typename function='substr(@me,0,8)'/]</a></LI>\r\n",57,324);
$z[0][4]['row']="9";
$z[0][4]['type']="sun";
$z[0][4]['currentstyle']="<li><a href='~typelink~' class='red'>~typename~</a> </li>";
$z[1]=Array("global","",482,504);
$z[1][4]['name']="cfg_fax";
$z[2]=Array("global","",527,549);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",572,595);
$z[3][4]['name']="cfg_mail";
$z[4]=Array("global","",618,644);
$z[4][4]['name']="cfg_address";

?>