<?php
$z[0]=Array("field","",242,264);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",265,291);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",332,354);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",394,445);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",855,892);
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",1042,1071);
$z[5][4]['name']="typename";
$z[6]=Array("include","",1081,1116);
$z[6][4]['filename']="left.htm";
$z[7]=Array("field","",1197,1226);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n        <LI><SPAN>[field:pubdate function=\"GetDateMK(@me)\"/]</SPAN><a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</A></LI>\r\n       ",1302,1491);
$z[8][4]['pagesize']="15";
$z[9]=Array("pagelist","",1551,1622);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",1666,1703);
$z[10][4]['filename']="footer.htm";

?>